version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Ah123456789Ah
      MYSQL_DATABASE: users
      MYSQL_USER: root
      MYSQL_PASSWORD: Ah123456789Ah
    ports:
      - "3307:3306" 
    volumes:
      - mysql_data:/var/lib/mysql

  wildfly:
    image: jboss/wildfly:latest
    container_name: wildfly_app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
      - "9990:9990"
    # volumes:
    #   - ./standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml
    #   - ./target/User-Service-1.0-SNAPSHOT.war:/opt/jboss/wildfly/standalone/deployments/target/User-Service-1.0-SNAPSHOT.war
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=users
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Ah123456789Ah
    command: ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0"] # Corrected command

volumes:
  mysql_data:
